---
# inventory/hosts.yml
#
# NOMMA Linux server inventory for CIS hardening.

all:
  children:
    nomma_linux:
      children:
        offline_root_ca:
          hosts:
            NOMMA-ROOTCA01:
              ansible_host: 10.1.2.97
              ansible_user: ldecareaux
              ansible_become: true
            NOMMA-LINUX:
              ansible_host: 192.168.122.193
              ansible_user: liam
              ansible_become: true
